export interface PlanetInfo {
  id: string;
  name: string;
  nameCN: string;
  color: string;
  size: number;
  distance: number;
  period: number;
  description: string;
  module: string;
  summary: string;
  route: string;
}

export const PLANET_DATA: Record<string, PlanetInfo> = {
  sun: {
    id: 'sun',
    name: 'Sun',
    nameCN: '太阳',
    color: '#FDB813',
    size: 3,
    distance: 0,
    period: 0,
    module: '站点核心',
    route: '/module/sun',
    summary: '整个 OrbitLog 的入口、时间线和导航中心。',
    description: '这里聚合最新文章、最近照片、项目入口和个人状态，是太阳系博客的中枢。',
  },
  mercury: {
    id: 'mercury',
    name: 'Mercury',
    nameCN: '水星',
    color: '#b9a17a',
    size: 0.38,
    distance: 0.39,
    period: 0.24,
    module: '博客文章',
    route: '/module/mercury',
    summary: '短小、快速、靠近灵感源头的文章归档。',
    description: '水星代表博客。这里存放日常随笔、技术笔记、读书摘录和今天刚写下的 Markdown。',
  },
  venus: {
    id: 'venus',
    name: 'Venus',
    nameCN: '金星',
    color: '#ffc85a',
    size: 0.95,
    distance: 0.72,
    period: 0.62,
    module: '灵感与审美',
    route: '/module/venus',
    summary: '收藏影像、设计、音乐、句子和审美参考。',
    description: '金星像一层浓厚发光的大气，适合放所有让你心动但暂时不必解释的灵感。',
  },
  earth: {
    id: 'earth',
    name: 'Earth',
    nameCN: '地球',
    color: '#4ea4ff',
    size: 1,
    distance: 1,
    period: 1,
    module: '个人简介',
    route: '/module/earth',
    summary: '关于我、经历、技能、现在正在做什么。',
    description: '地球代表个人简介。森林、海洋、蓝天作为背景，展示最像“家”的那部分信息。',
  },
  mars: {
    id: 'mars',
    name: 'Mars',
    nameCN: '火星',
    color: '#d96a4a',
    size: 0.53,
    distance: 1.52,
    period: 1.88,
    module: '项目与实验',
    route: '/module/mars',
    summary: '放置作品、原型、失败实验和正在建造的东西。',
    description: '火星代表探索和建造。页面可以用荒凉山脉、红色岩层、基地感边框来承载项目记录。',
  },
  jupiter: {
    id: 'jupiter',
    name: 'Jupiter',
    nameCN: '木星',
    color: '#d1a067',
    size: 1.4,
    distance: 5.2,
    period: 11.86,
    module: '兴趣宇宙',
    route: '/module/jupiter',
    summary: '兴趣、长期主题、收藏夹和反复回来的问题。',
    description: '木星代表兴趣。它足够大，可以容纳编程、电影、摄影、游戏、阅读等多个条带。',
  },
  saturn: {
    id: 'saturn',
    name: 'Saturn',
    nameCN: '土星',
    color: '#e4bb83',
    size: 1.2,
    distance: 9.58,
    period: 29.46,
    module: '相册与生活',
    route: '/module/saturn',
    summary: '照片、旅行、生活碎片，以及猫咪相册。',
    description: '土星代表相册。行星环像一卷胶片，适合收纳生活照片、旅行记录和可爱的日常。',
  },
  uranus: {
    id: 'uranus',
    name: 'Uranus',
    nameCN: '天王星',
    color: '#80e4ed',
    size: 4,
    distance: 19.2,
    period: 84,
    module: '知识库',
    route: '/module/uranus',
    summary: '冷静、结构化的笔记系统和索引。',
    description: '天王星代表知识库，适合放系统化学习笔记、概念地图、工具清单和长期维护的资料。',
  },
  neptune: {
    id: 'neptune',
    name: 'Neptune',
    nameCN: '海王星',
    color: '#5276ff',
    size: 3.88,
    distance: 30.05,
    period: 164.8,
    module: '未来计划',
    route: '/module/neptune',
    summary: '愿望清单、路线图、远方计划和还没抵达的事。',
    description: '海王星代表未来计划。这里放长期目标、旅行愿望、产品路线和那些看起来很远但会慢慢靠近的东西。',
  },
};
